### ISSUE TITLE
Composer

### ISSUE THREAD

**Issue by gam6itko** [lovattj/php-skydrive#8]
Can you add composer.json to the project? Also you need to bring you class to PSR-4 
https://github.com/php-fig/fig-standards/blob/master/proposed/psr-4-autoloader/psr-4-autoloader.md

**Comment by lovattj** [comment]
I've added Composer but I'll need to look into the PSR-4 specs first, give me a couple of days.

**Comment by gam6itko** [comment]
I can do that, if you allow
